### ISSUE TITLE
Package not available in Risset

### ISSUE THREAD

**Issue by jasonhallen** [gogins/csound-webserver-opcodes#21]
Hi Mike,

Under the Installation section of the README it says the webserver opcodes are available as a package in Risset.  However, when I list the Risset packages available I don't see this one.  Can you please make it available through Risset?

Thanks!
Jason

**Comment by gogins** [comment]
I will try to make it available in Risset. That means I have to submit a
merge request to the risset-data repository, and then Eduardo Moguillansky
has to do a merge.

In the meantime, you can just download the release zip file from my
repository, the most recent one for macOS is here:
https://github.com/gogins/csound-cxx-opcodes/releases/download/macos-latest/csound-cxx-opcodes-1.3.0-Darwin.zip.
Installation instructions are at the bottom of README.md. If you have
questions, ask right away.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by jasonhallen** [comment]
Thanks, Mike.  You linked me to the release for your csound-cxx-opcodes rather than the csound-webserver-opcodes which I'm interested in.  I found the latest MacOS development release for the webserver opcodes here: https://github.com/gogins/csound-webserver-opcodes/releases/tag/macos-latest.  However, the installation instructions still refer to Risset.

In any case, I'd be delighted if you and Eduardo could make this available through Risset.  Thanks!

Jason

**Comment by jasonhallen** [comment]
Oops, sorry, accidentally closed this.

**Comment by jasonhallen** [comment]
Thank you, Mike!  I'm looking at these instructions for installing plugins:
https://csound-plugins.github.io/csound-plugins/Installation.html.  Does
this mean that rather than updating the OPCODE6DIR64 variable I can now
drop the unpacked archive into ~/Library/csound/6.0/plugins64?

Thanks,
Jason

**Comment by gogins** [comment]
You can drop the dylib file there.

**Comment by jasonhallen** [comment]
Thanks for your help in this.  I was able to install your opcodes and get the bare-test.csd running on my computer!  I'm an beyond excited about the possibilities your opcodes have opened up.  Thanks!

Jason
